id: P009598
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W148
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་དཀའ་འགྲེལ།
  author: ''
  volumes:
    bc445702f4b145beab4a1882810d6e9a:
      image_group_id: I1KG10320
      title: ''
      volume_number: 1
      total_pages: 472
      base_file: v001.txt
